/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#47464e",
        "surface-container-low": "var(--surface-container-low)",
        "tertiary-fixed-dim": "#c8c5cd",
        "on-tertiary-fixed": "#1b1b20",
        "tertiary-fixed": "#e4e1e9",
        "inverse-primary": "#732ee4",
        "background": "var(--background)",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "var(--on-secondary-container)",
        "primary": "var(--primary)",
        "on-error": "#690005",
        "surface-variant": "var(--surface-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "error": "#ffb4ab",
        "secondary": "#c8c5cf",
        "inverse-on-surface": "#2f2f3c",
        "on-tertiary": "#303036",
        "secondary-container": "var(--secondary-container)",
        "on-primary": "#3f008e",
        "secondary-fixed-dim": "#c8c5cf",
        "secondary-fixed": "#e4e1eb",
        "on-surface-variant": "var(--on-surface-variant)",
        "error-container": "#93000a",
        "primary-container": "var(--primary-container)",
        "surface-dim": "var(--background)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-secondary": "#303037",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "var(--primary)",
        "outline": "#958da1",
        "on-primary-fixed-variant": "#5a00c6",
        "outline-variant": "var(--outline-variant)",
        "surface": "var(--surface)",
        "tertiary": "#c8c5cd",
        "on-primary-fixed": "#25005a",
        "on-secondary-fixed": "#1b1b22",
        "surface-container-high": "var(--surface-container-high)",
        "surface-bright": "var(--surface-bright)",
        "on-tertiary-fixed-variant": "#47464c",
        "surface-container": "var(--surface-container)",
        "on-surface": "var(--on-surface)",
        "tertiary-container": "#67666c",
        "inverse-surface": "var(--on-surface)",
        "surface-tint": "var(--primary)",
        "on-background": "var(--on-background)",
        "on-tertiary-container": "#e8e5ec"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-code": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
