/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#47464e",
        "surface-container-low": "#1a1b26",
        "tertiary-fixed-dim": "#c8c5cd",
        "on-tertiary-fixed": "#1b1b20",
        "tertiary-fixed": "#e4e1e9",
        "inverse-primary": "#732ee4",
        "background": "#12121e",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#bdbac4",
        "primary": "#d2bbff",
        "on-error": "#690005",
        "surface-variant": "#333440",
        "on-primary-container": "#ede0ff",
        "error": "#ffb4ab",
        "secondary": "#c8c5cf",
        "inverse-on-surface": "#2f2f3c",
        "on-tertiary": "#303036",
        "secondary-container": "#4b4a53",
        "on-primary": "#3f008e",
        "secondary-fixed-dim": "#c8c5cf",
        "secondary-fixed": "#e4e1eb",
        "on-surface-variant": "#ccc3d8",
        "error-container": "#93000a",
        "primary-container": "#7c3aed",
        "surface-dim": "#12121e",
        "surface-container-lowest": "#0c0d18",
        "surface-container-highest": "#333440",
        "on-secondary": "#303037",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "outline": "#958da1",
        "on-primary-fixed-variant": "#5a00c6",
        "outline-variant": "#4a4455",
        "surface": "#12121e",
        "tertiary": "#c8c5cd",
        "on-primary-fixed": "#25005a",
        "on-secondary-fixed": "#1b1b22",
        "surface-container-high": "#282935",
        "surface-bright": "#383845",
        "on-tertiary-fixed-variant": "#47464c",
        "surface-container": "#1e1f2a",
        "on-surface": "#e2e1f1",
        "tertiary-container": "#67666c",
        "inverse-surface": "#e2e1f1",
        "surface-tint": "#d2bbff",
        "on-background": "#e2e1f1",
        "on-tertiary-container": "#e8e5ec"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-code": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
